### PR TITLE
OCaml style externals.

### PR DESCRIPTION
**Pull request by andrejbauer**
Declare externals with a top-level command

    external foo : mlschema = "bar"

This follows OCaml and Eff syntax. The benefit is that we can write down the type in a
humane way, instead of having to put it in the OCaml source.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Doesn't that mean we can declare externals with an incorrect type? Having to write types in OCaml isn't bad enough to make me want that tradeoff.

**Comment by SkySkimmer** [comment]
The Andromeda runtime promises that the mltype of `external "print"` is correct just as it promises that the mltype of some complicated match statement is correct.

The issue is really that "external" is a bad name. In Ocaml externals can be user code, so it makes sense to have the user give their type, but in Andromeda externals are part of the system. The only user visible difference between having `external "print"` and having a `print` keyword is that the user can bind the `print` ident to whatever they like.

If someday we add a plugin system allowing the user to call their own Ocaml code having those functions declare their type in AML instead of in the plugin ala Ocaml externals may make sense, but I just don't see it for the current system.

**Comment by andrejbauer** [comment]
As I said already, I am doing this to keep compatibility with OCaml. If you'd like to change the `external` keyword, fine, suggest one.

**Comment by andrejbauer** [comment]
@SkySkimmer how badly do you object to this? If you're not totally horrified by it, I'd like to have it pulled it.

**Comment by SkySkimmer** [comment]
Are these differences with Ocaml intentional:
- `external foo : bar = "baz"` prints `val foo : bar` where Ocaml prints `external foo : bar = "baz"` (Eff appears to print nothing when I try http://www.eff-lang.org/try/ with `external ( = ) : 'a -> 'a -> bool = "="`)
- the existence of the external is checked at declaration time instead of use time (Eff checks at declaration time)
- externals have no access to their call location (Ocaml has this since eg __LOC__ is an external, we used it for the error when passing silliness to `external "config"`) (Eff doesn't give locations to externals, and uses the unknown location for errors eg https://github.com/matijapretnar/eff/blob/master/src/runtime/external.ml#L109 ).

**Comment by SkySkimmer** [comment]
Will pull after answer unless the answer says you want something changed first.

**Comment by andrejbauer** [comment]
Thanks for checking carefully, I'll deal with these.

**Comment by andrejbauer** [comment]
1. I fixed the printing so that it works as in OCaml.
2. The existence of the external is checked at declaration, there is no point in rechecking all the time.
3. I agree that access to location is needed. However, rather than creating an ad-hoc solution, I intend to change the monad so that the location is available. In fact, I will change the monad so that we'll have stack traces to print out when errors occur. I will do this in a separate PR. This PR can either wait for that, or you can merge it now, and I'll fix the externals when I get around to having stack-traces.

**Comment by SkySkimmer** [comment]
I don't understand what the monad has to do with access to the location but I guess I'll see when you do it.
Or maybe you can make an issue about it with details?

**Pull request merged**
