### PR TITLE
Implement strong normal form reduction

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Currently the snf of a structure `{x := e, y := x}` is `{x := snf e, y := x}`. This could be changed to `{x := snf e, y := snf e}`.

**Comment by andrejbauer** [comment]
Is there a plan to add rewriting by beta hints later?

**Comment by SkySkimmer** [comment]
What do you mean? It's just doing whnf then snf on every subterm, so beta hints are already used.

**Comment by haselwarter** [comment]
LGTM. The current solution of keeping structures folded seems reasonable.

**Comment by haselwarter** [comment]
Btw, could the user write her own [snf] using [whnf] and pattern matching?

**Pull request merged**
