### PR TITLE
Mathjax over correct protocol and misc improvements

### PR DESCRIPTION
**Pull request by SkySkimmer**
`//` means use the current protocol. Otherwise when using https mathjax gets blocked as mixed content (at least for my setup).

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I'm correcting typos with lots of git amends (to check the effect on my gitpages) so don't pull from this quite yet.

**Comment by andrejbauer** [comment]
Excellent, thank you!

**Comment by SkySkimmer** [comment]
That should be all for now.

**Comment by andrejbauer** [comment]
For `gh-pages` we do *not* have a one-pair-of-eyes strategy, so feel free to pull when you're done.

**Comment by andrejbauer** [comment]
Dont' forget to change the table of contents (Printing -> Externals).

**Comment by andrejbauer** [comment]
The only thing that is slightly annoying about this PR is that when I work with the pages locally they are served by jekyll through the `file:` protocol, and the MathJax does not work.

**Pull request merged**
