### PR TITLE
Thread env through a monad, pure state, lists

### PR DESCRIPTION
**Pull request by SkySkimmer**
Replaces #140, #141

The Value.result monad now contains the environment. It is divided into
- a state, which implements references, behaving like the usual monadic state
- a lexical environment, for lexically scoped data (mostly name bindings)
- a dynamic environment, which can be seen as the lexical environment at the call site for closures and operation handlers

Functions changing the environment in Value.result have been changed from

    val foo : 'i -> env -> 'o * env
    let y,env = foo x env in bar
to

    val foo : 'i -> ('o -> 'a result) -> 'a result
    foo x (fun y -> bar)
(the environment is locally changed in bar)
There is probably some better syntax for this.
This of course does not apply for state changes (which currently only happen when evaluating Syntax.Ref | Lookup | Update).

There is also a Value.toplevel monad which makes the whole environment state.
Note that at the toplevel the lexical and dynamic environments evolve in the same way.

Finally we still thread the environment manually in 2 places: desugaring and matching.
In desugar this is mostly because the environment is not modified (locally bound variables are not bound to any values, there's only the name list which is not part of the environment) so changing it would be pointless.
In matching this is because we use exceptions to signal failure to match, and this doesn't play well with the result monad. I started changing it to use an overlayed monad like Equal.Opt but it was annoying and there was no point.

I like that there's a separation between the valid accesses to the environment depending on which monad we're in. For instance we don't add constants inside computations (add_constant is in the toplevel monad).

The tests have been fixed to use state for the top level hint handler. The user mode equality checking loops on some (the looping stuff is commented out, so you can still do make test. grep TODO to find it) and is generally a bit ad-hoc so I'll be looking at that.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Also closes #136

**Comment by andrejbauer** [comment]
Is there a problem with garbage collecting stale state?

**Comment by SkySkimmer** [comment]
Only if we produce literally millions of temporary references.
Since state can be done with handlers except at the top level, which doesn't loop unless you do recursive includes, practical examples probably have a small constant number of permanent references (like  how we have top_betas and top_hints).

**Comment by SkySkimmer** [comment]
If it ever does become a problem, it should be possible to make something like WeakTbl (https://github.com/ocaml-batteries-team/batteries-included/blob/master/src/batInnerWeaktbl.ml) but as an immutable Map.

**Comment by andrejbauer** [comment]
I don't like the fact that there is a memory leak, but I'll merge anyway. In the long run I would prefer a solution in which the memory leak is not a problem.

**Pull request merged**
