### PR TITLE
Add a `random_choice v_true v_false' external

### PR DESCRIPTION
**Pull request by haselwarter**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Why?

**Comment by andrejbauer** [comment]
I think @haselwarter  was under the influence of the Dagstuhl workshop where every talk had an example of how to implement random choice.

**Comment by haselwarter** [comment]
how else would you drunkenly flip a coin?! apparently that's something you need to be able to do.

**Comment by SkySkimmer** [comment]
There should be a test for it.

**Comment by andrejbauer** [comment]
Well, it's not like the OCaml random stuff is *really* random. It's just a pseudo-random number generator that could be implemented in AML.

**Pull request closed without merging**
