### PR TITLE
Assumptions should always be the transitive closure thereof

### PR DESCRIPTION
**Pull request by SkySkimmer**
This should simplify the paper ;)

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Actually on second thought I'm not sure if this works well with joins. DO NOT MERGE unless you know otherwise.

**Comment by andrejbauer** [comment]
Can you explain a bit more what the purpose of this is. I thought we were already keeping assumption sets closed by transitivity. Apprently not. I must be thinking of the transitivity closure of assumptions on terms (if `t` is a substerm of `s` then the assumptions of `t` are included in assumptions of `s`).

**Comment by SkySkimmer** [comment]
There is the subterm transitivity you talk about, which we do have.
There is also the context transitivity, ie in master we have `T : Type, x : T |- x^{x} : T^{T}` and this would make it `T : Type, x : T |- x^{x, T} : T^{T}`.
The former means that the context restriction in the theorem "if `G |- e^a : T` then `G_a |- e : T`" needs to be more complicated.
The latter means that when we do a context join we need to preserve the property that any assumption set which is transitive for one of the contexts being joined is transitive for the join.

When I made the PR I thought it would be a good idea to switch to the later but now I'm not sure anymore.

**Comment by andrejbauer** [comment]
So, what's the verdict?

**Comment by andrejbauer** [comment]
The assumptions are gone in Andromeda 2.0 and this PR is two years old. We could possibly merge it into Andromeda 1.0, which would then require the creation of a separate branch and a separate life for Andromeda 1.0. Who is going to keep it alive? Nah, let's just close this.

**Pull request closed without merging**
