### PR TITLE
Lists

### PR DESCRIPTION
**Pull request by andrejbauer**
This pull request is on top of #140, please process that one first.

### CODE REVIEW

**Comment by andrejbauer** [comment]
Should I be helping with merging this?

**Comment by SkySkimmer** [comment]
I'll do it tomorrow.

**Comment by andrejbauer** [comment]
But I would need it for the demo tomorrow. Is there a version which I can demo?

**Comment by andrejbauer** [comment]
Oops, closed by mistake.

**Comment by SkySkimmer** [comment]
What is needed for a demo that's not in master?

**Comment by SkySkimmer** [comment]
Merged in https://github.com/SkySkimmer/andromeda/tree/monads
I'll make a pull request later, time for food.

**Pull request closed without merging**
