### PR TITLE
Let patterns

### PR DESCRIPTION
**Pull request by andrejbauer**
This PR introduces let-patterns:

    let (?p) = c1 in c2

is equivalent to

    match c1 with p => c2 end

### CODE REVIEW

**Comment by SkySkimmer** [comment]
How about patterns in function arguments as well?
Then typeof could be `let typeof (|- _ : ?A) = A` and `let typeof = fun (|- _ : ?A) => A` for instance.

**Comment by andrejbauer** [comment]
I'll resolve the conflicts.

**Comment by andrejbauer** [comment]
Re "patterns in function arguments": sure, and another enhancement is to allow let-patterns to be combined with ordinary let in parallel lets. I just wanted to get this working first, we can build on top of it.

**Comment by andrejbauer** [comment]
I made the let-patterns compatible with ordinary patterns, i.e., we can freely mix them, and also put typing annotations on the pattern variables.

The one thing that remains are patterns in function arguments. I would like to leave that as a separate PR because there is a parsing issue. If we want all four variants:

1. `fun x => ...`
2. `fun (x :> t) => ...`
3. `fun (?p) => ...`
4. `fun (?p :> t) => ...`

then there is a parsing ambiguity that I need to get rid of. So I hope this can be pulled now.

**Pull request merged**
