### PR TITLE
Do not use `_` as identifier, close #334

### LINKED ISSUE #334: Printing of underscores
Sometimes underscores `_` are printed. This happens when `_` is refreshed. The refreshing code shoudl turn it into something that is not `_`.

### PR DESCRIPTION
**Pull request by andrejbauer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Any tests for #334 ?

**Comment by andrejbauer** [comment]
Let me create one and ammend.

**Comment by andrejbauer** [comment]
It's not a perfect solution, but I think at least we won't see surprising `_`. There might be other examples where `_` appears. If it does, I'll just fix that too. The whole thing is a bit ad hoc.

**Comment by SkySkimmer** [comment]
Some test is failing in travis.

**Comment by andrejbauer** [comment]
They're ok now.

**Pull request merged**
