### PR TITLE
Add a license for Andromeda

### PR DESCRIPTION
**Pull request by andrejbauer**
This pull request is non-trivial because it involves licensing. So far we have had no license at all, which is bad. I am proposing a BSD 2-clause license, but I would like the current authors to agree first. They are @haselwarter, @christopherastone, @matijapretnar, and @SkySkimmer. Please confirm that you are ok with the license. The last person can then pull.

### CODE REVIEW

**Comment by matijapretnar** [comment]
I am ok with the license.

**Comment by haselwarter** [comment]
I am ok with the license.

**Comment by christopherastone** [comment]
Seems fine!

**Comment by SkySkimmer** [comment]
Here we go then.

**Pull request merged**
