### PR TITLE
Rename `fail` to `dont`

### PR DESCRIPTION
**Pull request by andrejbauer**
I think we need a sense of humor, such as it is. This is on top of #265.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
It's spelled "don't".

**Comment by andrejbauer** [comment]
Yeah, but I don't want to have a keyword with an apostrophe in the middle.

**Comment by andrejbauer** [comment]
A really evil thing would be `do not`.

**Comment by SkySkimmer** [comment]
>Yeah, but I don't want to have a keyword with an apostrophe in the middle.

Why not?

We could have `run` and `walk`.

**Comment by andrejbauer** [comment]
And `crawl`.

**Comment by andrejbauer** [comment]
I brought this PR up to speed with master. Are we going to merge it? (I do not care too much either way, but we should decide.)

**Comment by andrejbauer** [comment]
@SkySkimmer doesn't like this.

**Pull request closed without merging**
