### PR TITLE
Prevent top-level shadowing, close #137

### LINKED ISSUE #137: Better shadowing
If we do something like

    let x = foo
    constant x : bar

there is no way to refer to the constant `x` because top level declarations are always shadowed by bound variables.
This is silly.

### PR DESCRIPTION
**Pull request by andrejbauer**
Apart from preventing top-level shadowing of any kind, this also accidentally pulls in the slides for my MAP 2016 talk. Sorry.

There was a bit of shadowing in `std` files. I hope I fixed it correctly.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
equal_handle.m31 needs top level shadowing to work. See eg https://github.com/SkySkimmer/andromeda/blob/equal-tac/tests/beta-sum.m31
We need to modify the top level handling depending on a parameter (the action variable). Since it's the top level parameter we can't use a function to do it, so instead we include the equal_handle.m31 file. We need to do so several times, and the variable needs to have the same name every time, so it needs top level shadowing.
Therefore it can't be fixed.

**Comment by andrejbauer** [comment]
Ok, that's just a very very ugly hack. I am implementing state right now, will that help? If not, what would help?

**Comment by SkySkimmer** [comment]
State should help yes.

**Comment by SkySkimmer** [comment]
What are those .key files?

**Comment by SkySkimmer** [comment]
Replaced by #143

**Comment by andrejbauer** [comment]
The .key files are Keynote presentations of my talks. I am not sure they belong here, but on the other hand they are talks about Andromeda.

**Comment by SkySkimmer** [comment]
Are they compiled from something, or are they sources?

**Comment by andrejbauer** [comment]
They are the sources. I could place PDFs next to them.

**Comment by haselwarter** [comment]
That would be nice, I couldn't find a viewer for them.

**Comment by andrejbauer** [comment]
Apple will readily sell you a viewer :-) And I can probably share them online via Apple's magic.

**Pull request closed without merging**
